services:
  - type: web
    name: drive-search-backend
    env: docker
    branch: main
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /
    plan: free

    envVars:
      - key: SERVICE_ACCOUNT_FILE
        value: /etc/secrets/service-account.json

      - key: DRIVE_FOLDER_ID
        sync: false

      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: drive-search-frontend
    env: docker
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: free

    envVars:
      - key: BACKEND_URL
        value: https://drive-search-backend.onrender.com